// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMS.Api.Data;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727070414_FixSectionTableMapping")]
    partial class FixSectionTableMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SMS.Api.Models.AcademicClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AcademicClass");
                });

            modelBuilder.Entity("SMS.Api.Models.Admission", b =>
                {
                    b.Property<long>("AdmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("admission_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AdmissionId"));

                    b.Property<string>("AdmissionType")
                        .HasColumnType("longtext")
                        .HasColumnName("admission_type");

                    b.Property<string>("ApplicationNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("application_no");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("longtext")
                        .HasColumnName("blood_group");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Caste")
                        .HasColumnType("longtext")
                        .HasColumnName("caste");

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dob");

                    b.Property<string>("FatherMobile")
                        .HasColumnType("longtext")
                        .HasColumnName("father_mobile");

                    b.Property<string>("FatherName")
                        .HasColumnType("longtext")
                        .HasColumnName("father_name");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext")
                        .HasColumnName("gender");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("student_name");

                    b.HasKey("AdmissionId");

                    b.ToTable("admissions");
                });

            modelBuilder.Entity("SMS.Api.Models.AdmissionApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternateMobileNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("AppliedClassId")
                        .HasColumnType("int");

                    b.Property<string>("AreaLocality")
                        .HasColumnType("longtext");

                    b.Property<string>("AvailableBed")
                        .HasColumnType("longtext");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("longtext");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BusRoute")
                        .HasColumnType("longtext");

                    b.Property<string>("Caste")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Discount")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("DropPoint")
                        .HasColumnType("longtext");

                    b.Property<string>("ExistingSiblingLookup")
                        .HasColumnType("longtext");

                    b.Property<string>("FatherContact")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FloorLevel")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HostelBlock")
                        .HasColumnType("longtext");

                    b.Property<string>("HostelRoom")
                        .HasColumnType("longtext");

                    b.Property<string>("HouseNo")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotherMobileNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("MotherName")
                        .HasColumnType("longtext");

                    b.Property<int>("NumberOfSiblings")
                        .HasColumnType("int");

                    b.Property<string>("ParentEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("PickupPoint")
                        .HasColumnType("longtext");

                    b.Property<string>("PinCode")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Religion")
                        .HasColumnType("longtext");

                    b.Property<string>("Scholarship")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.Property<bool>("TransportRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TransportType")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AppliedClassId");

                    b.ToTable("AdmissionApplications");
                });

            modelBuilder.Entity("SMS.Api.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("SMS.Api.Models.ClassCurriculumSubject", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("ClassGradeClassId")
                        .HasColumnType("int");

                    b.HasKey("ClassId", "SubjectId");

                    b.HasIndex("ClassGradeClassId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ClassCurriculumSubjects");
                });

            modelBuilder.Entity("SMS.Api.Models.ClassGrade", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ClassId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SMS.Api.Models.ClassSection", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassTeacherEmpId")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("SectionId");

                    b.HasIndex("ClassTeacherEmpId");

                    b.HasIndex("ClassId", "SectionName")
                        .IsUnique();

                    b.ToTable("section", (string)null);
                });

            modelBuilder.Entity("SMS.Api.Models.ExamClass", b =>
                {
                    b.Property<long>("ExamId")
                        .HasColumnType("bigint")
                        .HasColumnName("exam_id");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.HasKey("ExamId", "ClassId");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_exam_classes_class_id");

                    b.ToTable("exam_classes", (string)null);
                });

            modelBuilder.Entity("SMS.Api.Models.ExamMaster", b =>
                {
                    b.Property<long>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("exam_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ExamId"));

                    b.Property<long>("AcademicYearId")
                        .HasColumnType("bigint")
                        .HasColumnName("academic_year_id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("ExamStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Scheduled")
                        .HasColumnName("exam_status");

                    b.Property<string>("ExamTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("exam_title");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("exam_type");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.HasKey("ExamId");

                    b.HasIndex("ExamTitle", "BranchId", "AcademicYearId")
                        .IsUnique()
                        .HasDatabaseName("ux_exam_title_branch_academic_year");

                    b.HasIndex("BranchId", "AcademicYearId", "ExamStatus", "IsDeleted")
                        .HasDatabaseName("ix_exam_master_filter");

                    b.ToTable("exam_masters", (string)null);
                });

            modelBuilder.Entity("SMS.Api.Models.OtpVerification", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OtpCodeHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OtpId");

                    b.HasIndex("UserId");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("SMS.Api.Models.PickupPoint", b =>
                {
                    b.Property<long>("PickupPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("PickupPointId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DistanceFromStart")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Landmark")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("PickupPointName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<TimeSpan>("PickupTime")
                        .HasColumnType("time(6)");

                    b.Property<long>("RouteId")
                        .HasColumnType("bigint");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PickupPointId");

                    b.HasIndex("RouteId", "PickupPointName");

                    b.HasIndex("RouteId", "SequenceNo");

                    b.ToTable("transport_pickup_points", (string)null);
                });

            modelBuilder.Entity("SMS.Api.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SMS.Api.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<int>("AcademicClassId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SectionId");

                    b.HasIndex("AcademicClassId");

                    b.HasIndex("ClassTeacherId");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("SMS.Api.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("StaffId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("SMS.Api.Models.StudentTransportAssignment", b =>
                {
                    b.Property<long>("StudentTransportAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("StudentTransportAssignmentId"));

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<long>("PickupPointId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("RouteId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("VehicleAssignmentId")
                        .HasColumnType("bigint");

                    b.HasKey("StudentTransportAssignmentId");

                    b.HasIndex("PickupPointId");

                    b.HasIndex("RouteId");

                    b.HasIndex("StudentId");

                    b.HasIndex("VehicleAssignmentId");

                    b.HasIndex("StudentId", "EffectiveFrom", "EffectiveTo");

                    b.HasIndex("RouteId", "PickupPointId", "VehicleAssignmentId", "Status", "IsDeleted")
                        .HasDatabaseName("IX_STA_Route_Pickup_Vehicle");

                    b.ToTable("StudentTransportAssignments");
                });

            modelBuilder.Entity("SMS.Api.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int?>("AcademicClassId")
                        .HasColumnType("int");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SubjectId");

                    b.HasIndex("AcademicClassId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SMS.Api.Models.TransportDriver", b =>
                {
                    b.Property<long>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("DriverId"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("AlternateMobileNumber")
                        .HasColumnType("longtext");

                    b.Property<long?>("AssignedVehicleId")
                        .HasColumnType("bigint");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("longtext");

                    b.Property<string>("EmergencyContactNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LicenceExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("DriverId");

                    b.HasIndex("AssignedVehicleId");

                    b.HasIndex("LicenceNumber")
                        .IsUnique();

                    b.HasIndex("MobileNumber");

                    b.ToTable("TransportDrivers");
                });

            modelBuilder.Entity("SMS.Api.Models.TransportRoute", b =>
                {
                    b.Property<long>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("route_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RouteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("distance_km");

                    b.Property<string>("DropPoint")
                        .HasColumnType("longtext");

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("end_location");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PickupPoint")
                        .HasColumnType("longtext");

                    b.Property<string>("RouteCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("route_code");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("route_name");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("start_location");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<long?>("VehicleId")
                        .HasColumnType("bigint");

                    b.HasKey("RouteId");

                    b.HasIndex("RouteCode")
                        .IsUnique()
                        .HasDatabaseName("ux_transport_routes_route_code");

                    b.HasIndex("RouteName")
                        .IsUnique()
                        .HasDatabaseName("ux_transport_routes_route_name");

                    b.HasIndex("VehicleId");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("ix_transport_routes_status_is_deleted");

                    b.ToTable("transport_routes", (string)null);
                });

            modelBuilder.Entity("SMS.Api.Models.TransportVehicle", b =>
                {
                    b.Property<long>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("VehicleId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ChassisNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("EngineNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FitnessExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GpsDeviceId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("InsuranceExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InsuranceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsAC")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("PollutionExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("VehicleId");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("VehicleNumber")
                        .IsUnique();

                    b.ToTable("transport_vehicles", (string)null);
                });

            modelBuilder.Entity("SMS.Api.Models.TransportVehicleAssignment", b =>
                {
                    b.Property<long>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AssignmentId"));

                    b.Property<long>("DriverId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("RouteId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint");

                    b.HasKey("AssignmentId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("RouteId", "VehicleId", "DriverId", "EffectiveFrom");

                    b.HasIndex("VehicleId", "DriverId", "RouteId", "Status", "IsDeleted")
                        .HasDatabaseName("IX_TVA_Vehicle_Driver_Route");

                    b.ToTable("TransportVehicleAssignments");
                });

            modelBuilder.Entity("SMS.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMobileVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SMS.Api.Models.VehicleMaintenance", b =>
                {
                    b.Property<long>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("maintenance_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("MaintenanceId"));

                    b.Property<decimal>("Cost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("NextServiceDue")
                        .HasColumnType("date")
                        .HasColumnName("next_service_due");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remarks");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("date")
                        .HasColumnName("service_date");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("service_type");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("VendorCenter")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("vendor_center");

                    b.HasKey("MaintenanceId");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("IX_transport_vehicle_maintenance_vehicle_id");

                    b.HasIndex("VehicleId", "ServiceDate", "IsDeleted")
                        .HasDatabaseName("IX_VehMaint_Vehicle_ServiceDate_Deleted");

                    b.ToTable("transport_vehicle_maintenance", (string)null);
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SMS.Api.Models.AdmissionApplication", b =>
                {
                    b.HasOne("SMS.Api.Models.ClassGrade", "AppliedClass")
                        .WithMany("AdmissionApplications")
                        .HasForeignKey("AppliedClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppliedClass");
                });

            modelBuilder.Entity("SMS.Api.Models.ClassCurriculumSubject", b =>
                {
                    b.HasOne("SMS.Api.Models.ClassGrade", "ClassGrade")
                        .WithMany("CurriculumSubjects")
                        .HasForeignKey("ClassGradeClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMS.Api.Models.Subject", "Subject")
                        .WithMany("CurriculumSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassGrade");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SMS.Api.Models.ClassSection", b =>
                {
                    b.HasOne("SMS.Api.Models.ClassGrade", "ClassGrade")
                        .WithMany("Sections")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMS.Api.Models.Staff", "ClassTeacher")
                        .WithMany()
                        .HasForeignKey("ClassTeacherEmpId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClassGrade");

                    b.Navigation("ClassTeacher");
                });

            modelBuilder.Entity("SMS.Api.Models.ExamClass", b =>
                {
                    b.HasOne("SMS.Api.Models.ClassGrade", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMS.Api.Models.ExamMaster", "Exam")
                        .WithMany("ExamClasses")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("SMS.Api.Models.OtpVerification", b =>
                {
                    b.HasOne("SMS.Api.Models.User", "User")
                        .WithMany("OtpVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SMS.Api.Models.PickupPoint", b =>
                {
                    b.HasOne("SMS.Api.Models.TransportRoute", "TransportRoute")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TransportRoute");
                });

            modelBuilder.Entity("SMS.Api.Models.Section", b =>
                {
                    b.HasOne("SMS.Api.Models.AcademicClass", "AcademicClass")
                        .WithMany("Sections")
                        .HasForeignKey("AcademicClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMS.Api.Models.Staff", "ClassTeacher")
                        .WithMany("SectionsTaught")
                        .HasForeignKey("ClassTeacherId");

                    b.Navigation("AcademicClass");

                    b.Navigation("ClassTeacher");
                });

            modelBuilder.Entity("SMS.Api.Models.StudentTransportAssignment", b =>
                {
                    b.HasOne("SMS.Api.Models.PickupPoint", "PickupPoint")
                        .WithMany()
                        .HasForeignKey("PickupPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMS.Api.Models.TransportRoute", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMS.Api.Models.TransportVehicleAssignment", "VehicleAssignment")
                        .WithMany()
                        .HasForeignKey("VehicleAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PickupPoint");

                    b.Navigation("Route");

                    b.Navigation("VehicleAssignment");
                });

            modelBuilder.Entity("SMS.Api.Models.Subject", b =>
                {
                    b.HasOne("SMS.Api.Models.AcademicClass", null)
                        .WithMany("Subjects")
                        .HasForeignKey("AcademicClassId");
                });

            modelBuilder.Entity("SMS.Api.Models.TransportDriver", b =>
                {
                    b.HasOne("SMS.Api.Models.TransportVehicle", "AssignedVehicle")
                        .WithMany("Drivers")
                        .HasForeignKey("AssignedVehicleId");

                    b.Navigation("AssignedVehicle");
                });

            modelBuilder.Entity("SMS.Api.Models.TransportRoute", b =>
                {
                    b.HasOne("SMS.Api.Models.TransportVehicle", "Vehicle")
                        .WithMany("Routes")
                        .HasForeignKey("VehicleId");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SMS.Api.Models.TransportVehicleAssignment", b =>
                {
                    b.HasOne("SMS.Api.Models.TransportDriver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMS.Api.Models.TransportRoute", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMS.Api.Models.TransportVehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Route");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SMS.Api.Models.VehicleMaintenance", b =>
                {
                    b.HasOne("SMS.Api.Models.TransportVehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("SMS.Api.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMS.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMS.Api.Models.AcademicClass", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("SMS.Api.Models.ClassGrade", b =>
                {
                    b.Navigation("AdmissionApplications");

                    b.Navigation("CurriculumSubjects");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SMS.Api.Models.ExamMaster", b =>
                {
                    b.Navigation("ExamClasses");
                });

            modelBuilder.Entity("SMS.Api.Models.Staff", b =>
                {
                    b.Navigation("SectionsTaught");
                });

            modelBuilder.Entity("SMS.Api.Models.Subject", b =>
                {
                    b.Navigation("CurriculumSubjects");
                });

            modelBuilder.Entity("SMS.Api.Models.TransportVehicle", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("SMS.Api.Models.User", b =>
                {
                    b.Navigation("OtpVerifications");
                });
#pragma warning restore 612, 618
        }
    }
}
